apt/urls.py
from django.conf.urls import url
from . import views

app_name = 'apt'

urlpatterns = [
    url(r'^$', views.make_appointment, name='make_appointment'),
    url(r'^success/$', views.apt_success, name='apt_success'),
]

hms/urls.py
from django.conf.urls import url
from . import views

app_name = 'hms'

urlpatterns = [
    url(r'^$', views.hospital_index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^hospitals/$', views.hospital_index, name='hospital_index'),
    url(r'^hospitals/(?P<pk>[0-9]+)/$', views.hospital_details, name='hospital_details'),
    url(r'^hospitals/(?P<pk>[0-9]+)/(?P<id>[0-9]+)/$', views.hospital_doctorlist, name='hospital_doctors'),
    url(r'^doctors/$', views.doctor_index, name='doctor_index'),
    url(r'^doctors/(?P<id>[0-9]+)/$', views.doctor_details, name='doctor_details'),
]

apt/models.py
from django.db import models
from hms.models import Hospital, Doctor

# Create your models here.

class Appointment(models.Model):
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE)
    patient_name = models.CharField(max_length=200)
    date = models.DateTimeField()

    def __str__(self):
        return self.patient_name + ' - ' + str(self.id) + ' - ' + self.doctor.name

hms/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from multiselectfield import MultiSelectField

# Create your models here.

class Hospital(models.Model):
    hospital_name = models.CharField(max_length=500)
    area = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    image = models.FileField()

    def __str__(self):
        return self.hospital_name

class Doctor(models.Model):

    HEALTH_ISSUES = (
        ('chest pain', 'chest pain'),
        ('suffocation', 'suffocation'),
        ('stomachache', 'stomachache'),
        ('toothache', 'toothache'),
        ('fever', 'fever'),
        ('allergy', 'allergy'),
        ('std', 'std'),
        ('constipation', 'constipation'),
        ('diarrhea', 'diarrhea'),
        ('dysentery', 'dysentery'),
        ('ulcer', 'ulcer'),
        ('child disease', 'child disease'),
        ('gastric', 'gastric'),
        ('marital issues', 'marital issues'),
        ('headache', 'headache'),
        ('mental condition', 'mental condition'),
        ('broken bone', 'broken bone'),
        ('fracture', 'fracture'),
        ('stroke', 'stroke'),
        ('nervous problems', 'nervous problems'),
        ('seizure', 'seizure'),
        ('swallowing', 'swallowing'),
    )

    SPECIALIZATION = (
        ('Cardiologist', 'Cardiologist'),
        ('Medicine', 'Medicine'),
        ('Dermatologist', 'Dermatologist'),
        ('Pediatrician', 'Pediatrician'),
        ('Gastroenterologist', 'Gastroenterologist'),
        ('Gynecologist', 'Gynecologist'),
        ('Neurologist', 'Neurologist'),
        ('Orthopedic', 'Orthopedic'),
        ('Psychiatrist', 'Psychiatrist'),
        ('Dentist', 'Dentist'),
    )

    name = models.CharField(max_length=200)
    hospital = models.ForeignKey(Hospital,on_delete=models.CASCADE)
    speciality = models.CharField(max_length=50,choices=SPECIALIZATION)
    health_issue = MultiSelectField(max_length=500,choices=HEALTH_ISSUES)
    dp = models.FileField()

    def __str__(self):
        return self.name + ' - ' + self.speciality

apt/forms.py
from django import forms
from hms.forms import UserForm
from .models import Appointment

class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['doctor', 'patient_name', 'date']

hms/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

apt/views.py
from django.shortcuts import render, get_object_or_404
from hms.models import Hospital, Doctor
from hms.forms import UserForm
from .models import Appointment
from .forms import AppointmentForm

# Create your views here.

def make_appointment(request):
    form = AppointmentForm(request.POST or None, request.FILES or None)
    #appointments = Appointment.objects.all()
    if form.is_valid():
        appointment = form.save(commit=False)
        '''
        for a in appointments:
            if appointment.date is not a.date:
                break
            else:
                return render(request, 'apt/apt_failed.html')
        '''
        appointment.save()
        return render(request, 'apt/apt_success.html', {'appointment': appointment})
    return render(request, 'apt/appointment.html', {'form': form})

def apt_success(request):
    return render(request, 'apt/apt_success.html')

hms/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import UserForm
from .models import Hospital, Doctor
from apt.models import Appointment
import operator

# Create your views here.

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'hms/login.html')
    else:
        return render(request, 'hms/index.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'hms/index.html')
            else:
                return render(request, 'hms/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'hms/login.html', {'error_message': 'Invalid login'})
    return render(request, 'hms/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'hms/login.html', context)


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'hms/index.html')
    context = {
        "form": form,
    }
    return render(request, 'hms/register.html', context)

def hospital_index(request):
    hospitals = sorted(Hospital.objects.all(),key=operator.attrgetter('hospital_name'))
    #doctors = sorted(Doctor.objects.all(),key=operator.attrgetter('name'))
    #context = {'hospitals': hospitals}
    #hospitals = Hospital.objects.all()
    doctors = Doctor.objects.all()
    query = request.GET.get("q")
    if query:
        doctors = doctors.filter(
            Q(speciality__icontains=query)|Q(health_issue__icontains=query)|Q(hospital__hospital_name__icontains=query)
        ).distinct()
        return render(request,'hms/search.html',{'doctors': doctors})
    else:
        return render(request,'hms/index.html', {'hospitals': hospitals})

def hospital_details(request,pk):
    hospital = get_object_or_404(Hospital, pk=pk)
    return render(request,'hms/hospital_details.html', {'hospital': hospital})

def doctor_index(request):
    doctors = sorted(Doctor.objects.all(),key=operator.attrgetter('name'))
    return render(request,'hms/doctor_index.html',{'doctors': doctors})

def doctor_details(request,id):
    doctor = get_object_or_404(Doctor, id=id)
    appointments = sorted(Appointment.objects.filter(doctor__id=id),key=operator.attrgetter('date'))
    #appointments = Appointment.objects.all()
    return render(request,'hms/doctor_details.html',{
        'doctor': doctor,
        'appointments': appointments,
    })

def hospital_doctorlist(request, pk, id):
    hospital = get_object_or_404(Hospital, pk=pk)
    doctor = hospital.doctor_set.get(id=id)
    appointments = sorted(Appointment.objects.filter(doctor__id=id),key=operator.attrgetter('date'))
    return render(request,'hms/doctor_details.html', {
        'doctor': doctor,
        'appointments': appointments,
    })

apt/templates/apt/appointment.html
{% extends 'hms/index.html' %}
{% block title %}appointment{% endblock %}
{% block make_apt %}active{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'apt/styleform.css' %}"/>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-custom">
                        <div class="panel-body">
                            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'apt/form_template.html' %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

<!--<div class="form-group">
    <label class="control-label col-sm-2">
        Doctor:
    </label>
    <div class="col-sm-10">
        <input maxlength="100" name="doctor" type="text">
    </div>
</div>-->

apt/templates/apt/apt_failed.html
{% extends 'hms/index.html' %}
{% block title %}appointment failed{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'apt/styleform.css' %}"/>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="alert alert-danger">
                Appointment failed. The requested date and time is occupied. Please select available date and time.
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

apt/templates/apt/apt_success.html
{% extends 'hms/index.html' %}
{% block title %}appointment successful{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'apt/styleform.css' %}"/>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="text-center">
                <h1 style="font-family:El Messiri; color:#2d948b;">Appoinment has been made successfully</h1>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

apt/templates/apt/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

hms/templates/hms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FindDoctor{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'hms/images/logo.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=El Messiri"/>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine"/>
    <link rel='stylesheet' type='text/css' href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'hms/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--<script src="{% static 'hms/js/main.js' %}"></script>-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hms:index' %}">FindDoctor</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'hms:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'hms:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

hms/templates/hms/doctor_details.html
{% extends 'hms/index.html' %}
{% block title %}{{doctor.name}} details{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hms/back.css' %}"/>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-offset-1 col-md-10">
                <div class="relative">
                    <img src="{{ doctor.dp.url }}" class="img-circle" width="250" height="250" style="border:10px solid #2d948b">
                    <br>
                    <h2 style="font-family:El Messiri; color:#2d948b;">{{doctor.name}}</h2>
                    <h3 style="font-family:El Messiri; color:#2d948b;">{{doctor.speciality}}</h3>
                    <h3 style="font-family:El Messiri; color:#2d948b;">{{doctor.hospital.hospital_name}}</h3>
                    <div class="alert alert-danger">Expert in treatment of {{doctor.health_issue}}</div>
                    <a href="{% url 'apt:make_appointment' %}" class="btn btn-primary btn-sm" role="button">Make Appointment</a>
                    <br>
                    <br>
                    <h3 style="font-family:El Messiri; color:black;">Current Appointments</h3>
                    {% if appointments %}
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Doctor</th>
                                    <th>Patient's Name</th>
                                    <th>Date and Time</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for a in appointments %}
                                <tr>
                                    <td>{{ a.doctor.name }}</td>
                                    <td>{{ a.patient_name }}</td>
                                    <td>{{ a.date }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

hms/templates/hms/doctor_index.html
{% extends 'hms/index.html' %}
{% block title %}Doctors{% endblock %}
{% block doctors_active %}active{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            {% for d in doctors %}
                <div class="col-xs-offset-1 col-md-7">
                    <div class="thumbnail text-center">
                        <div class="relative">
                            <br>
                            <a href="{% url 'hms:doctor_details' d.id %}">
                                <img src="{{ d.dp.url }}" class="img-circle" width="400" height="400" style="border:10px solid #2d948b">
                            </a><br>
                            <a style="font-family:El Messiri;font-size:24px;color:#2d948b;" href="{% url 'hms:doctor_details' d.id %}">&nbsp; {{d.name}}</a>
                            <h3 style="font-family:El Messiri; color:#2d948b;">{{d.hospital.hospital_name}}</h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

hms/templates/hms/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

hms/templates/hms/hospital_details.html
{% extends 'hms/index.html' %}
{% block title %}{{hospital.hospital_name}}{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'hms/back.css' %}"/>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-offset-1 col-md-5">
                <div class="relative">
                    <img src="{{ hospital.image.url }}" width="550" height="550" style="border:10px solid #2d948b">
                    <br>
                    <br>
                    <a style="font-family:El Messiri; font-size:34px; color:#2d948b;" href="">{{hospital.hospital_name}}</a>
                    <h2 style="font-family:El Messiri; color:#2d948b;">{{hospital.address}}</h2><br>
                </div>
            </div>
            <div class="col-md-5">
                <h2 style="font-family:El Messiri; color:#2d948b;">Doctor's List</h2>
                {% for i in hospital.doctor_set.all %}
                    <li><a style="font-family:El Messiri;font-size:24px;color:#2d948b;" href="{% url 'hms:hospital_doctors' i.hospital.pk i.id %}">{{ i.name }}</a></li>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

hms/templates/hms/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}FindDoctor{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'hms/images/logo.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">-->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=El Messiri"/>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine"/>
    <link rel='stylesheet' type='text/css' href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{% static 'hms/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'hms/thumbnail.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--<script src="{% static 'hms/js/main.js' %}"></script>-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hms:index' %}">FindDoctor</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block hospitals_active %}{% endblock %}">
                    <a style="font-family:El Messiri; font-size:18px;" href="{% url 'hms:hospital_index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Hospitals
                    </a>
                </li>
                <li class="{% block doctors_active %}{% endblock %}">
                    <a style="font-family:El Messiri; font-size:18px;" href="{% url 'hms:doctor_index' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Doctors
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'hms:index' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block make_apt %}{% endblock %}">
                    <a style="font-family:El Messiri; font-size:18px;" href="{% url 'apt:make_appointment' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Make Appoinment
                    </a>
                </li>
                <li>
                    <a style="font-family:El Messiri; font-size:18px;" href="{% url 'hms:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}
<div class="container-fluid">
    <div class="row">
        {% for h in hospitals %}
            <div class="col-xs-offset-1 col-md-8">
                <div class="thumbnail text-center">
                    <div class="relative">
                        <br>
                        <a href="{% url 'hms:hospital_details' h.id %}">
                            <img src="{{ h.image.url }}" width="750" height="500" style="border:10px solid #2d948b">
                        </a><br>
                        <a style="font-family:El Messiri; font-size:24px; color:#2d948b;" href="{% url 'hms:hospital_details' h.id %}">&nbsp; {{h.hospital_name}}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
</body>
</html>

<!-- url 'hms:hospital_details' h.id -->

hms/templates/hms/login.html
{% extends 'hms/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading panel-heading-custom">
                    <div class="panel-body">
                        <h3 style="font-family:El Messiri; font-size:30px;">Log In</h3>&nbsp;
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="{% url 'hms:login_user' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_username" maxlength="30" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-10">
                                    <input id="id_password" maxlength="30" name="password" type="password">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'hms:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

hms/templates/hms/register.html
{% extends 'hms/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading panel-heading-custom">
                    <div class="panel-body">
                        <h3 style="font-family:El Messiri; font-size:30px;" >Register for an Account</h3>&nbsp;
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'hms/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'hms:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

hms/templates/hms/search.html
{% extends 'hms/index.html' %}
{% block title %}{{doctor.name}} details{% endblock %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            {% if doctors %}
            {% for d in doctors %}
                <div class="col-xs-offset-1 col-md-7">
                    <div class="thumbnail">
                        <div class="relative">
                            <br>
                            <a href="{% url 'hms:doctor_details' d.id %}">
                                <img src="{{ d.dp.url }}" class="img-circle" width="400" height="400" style="border:10px solid #2d948b">
                            </a><br>
                            <a style="font-family:El Messiri;font-size:24px;color:#2d948b;" href="{% url 'hms:doctor_details' d.id %}">&nbsp; {{d.name}}</a>
                            <h3 style="font-family:El Messiri; color:#2d948b;">{{d.hospital.hospital_name}}</h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</body>
</html>
{% endblock %}